### PR TITLE
Add console commands

### PR DESCRIPTION
**Pull request by viktorprogger**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #24

### CODE REVIEW

**Comment by viktorprogger** [comment]
[Queue](https://trello.com/c/QTPMAx67/6-queue)

**Comment by roxblnfk** [comment]
I think in this case the `yiisoft/yii-console` requirement should be moved to `require` groupin `composer.json`

**Comment by samdark** [comment]
Also, it worth providing a config for console commands in `params.php`:

```php
 'console' => [
    'commands' => [
        'queue/run' => Yiisoft\Yii\Queue\Commands\RunCommand::class,
        'queue/listen' => Yiisoft\Yii\Queue\Commands\ListenCommand::class,
    ],
],
```

this way, command will be registered right after doing `composer require yiisoft/yii-queue`.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
